import 'package:ai_art_generator/constants/index.dart';
import 'package:ai_art_generator/models/art_data_model.dart';
import 'package:dio/dio.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:image_gallery_saver/image_gallery_saver.dart';
import 'package:path_provider/path_provider.dart';

class Details extends StatelessWidget {
  const Details({Key? key, required this.artDataModel}) : super(key: key);

  final ArtDataModel artDataModel;

  @override
  Widget build(BuildContext context) {
    _save() async {
      // var status = await Permission
      var response = await Dio().get(
          "https://ss0.baidu.com/94o3dSag_xI4khGko9WTAnF6hhy/image/h%3D300/sign=a62e824376d98d1069d40a31113eb807/838ba61ea8d3fd1fc9c7b6853a4e251f94ca5f46.jpg",
          options: Options(responseType: ResponseType.bytes));
      final result = await ImageGallerySaver.saveImage(
          Uint8List.fromList(response.data),
          quality: 60,
          name: "hello");
      print(result);
    }

    return Scaffold(
      backgroundColor: secondaryColor,
      extendBodyBehindAppBar: true,
      appBar: AppBar(
        backgroundColor: Colors.transparent,
        elevation: 0,
        leading: IconButton(
            onPressed: () {
              Navigator.pop(context);
            },
            icon: Icon(
              Icons.arrow_back_ios,
              color: normalWhite.withOpacity(0.8),
            )),
      ),
      body: SingleChildScrollView(
        child: Column(
          children: [
            ClipRRect(
              borderRadius: BorderRadius.circular(20),
              child: Image.network(
                artDataModel.image,
                fit: BoxFit.cover,
                width: MediaQuery.of(context).size.width * 1,
                height: MediaQuery.of(context).size.height * 0.7,
                loadingBuilder: (BuildContext context, Widget child,
                    ImageChunkEvent? loadingProgress) {
                  if (loadingProgress == null) return child;
                  return Center(
                    child: CircularProgressIndicator(
                      value: loadingProgress.expectedTotalBytes != null
                          ? loadingProgress.cumulativeBytesLoaded /
                              loadingProgress.expectedTotalBytes!
                          : null,
                    ),
                  );
                },
              ),
            ),
            const SizedBox(
              height: 16,
            ),
            Padding(
              padding: const EdgeInsets.all(20),
              child: Text(
                artDataModel.title,
                style: TextStyle(
                  wordSpacing: 1,
                  color: Colors.white.withOpacity(0.9),
                  fontSize: 17,
                ),
              ),
            ),
            Padding(
              padding: const EdgeInsets.all(20),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceAround,
                children: [
                  SizedBox(
                    width: MediaQuery.of(context).size.width * 0.25,
                    child: InkWell(
                      child: ElevatedButton(
                          style: ButtonStyle(
                              backgroundColor:
                                  MaterialStateProperty.all(secondaryLight)),
                          onPressed: () async {
                            // final imageUrl = artDataModel.image;
                            // final url = Uri.parse(imageUrl);
                            // final response = await http.get(url);
                            // final bytes = response.bodyBytes;

                            // final temp = await getTemporaryDirectory();
                            // final path = '${temp.path}/image.jpg';
                            // // File(path).writeAsBytesSync(bytes);

                            // await Share.shareXFiles([XFile(path)],
                            //     text: "image generated by AI");
                          },
                          child: const Icon(Icons.share)),
                    ),
                  ),
                  SizedBox(
                    width: MediaQuery.of(context).size.width * 0.25,
                    child: ElevatedButton(
                        style: ButtonStyle(
                            backgroundColor:
                                MaterialStateProperty.all(secondaryLight)),
                        onPressed: () {
                          _save();
                        },
                        child: const Icon(Icons.download)),
                  ),
                ],
              ),
            )
          ],
        ),
      ),
    );
  }
}
